version: '3.8'

services:

  mongo:
    image: mongo:4.4.6
    restart: always
    container_name: test1
    hostname: host-mongo
    environment:
      MONGO_INIT_ROOT_USERNAME: root
      MONGO_INIT_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db
      - ./data/log:/vas/log/mongodb/
    ports: 
      - "27017:27017"